# Generated by Django 5.0.7 on 2024-09-14 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elementCode', models.CharField(max_length=50)),
                ('elementType', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CopiedInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copiedInf', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copiedInf', to=settings.AUTH_USER_MODEL)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copiedInf', to='api.element')),
            ],
        ),
        migrations.CreateModel(
            name='Frecuency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valueCode', models.CharField(max_length=25)),
                ('value', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frecuency', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupportedServiced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceType', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supportedServices', to=settings.AUTH_USER_MODEL)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supportedServices', to='api.element')),
            ],
        ),
        migrations.CreateModel(
            name='Tape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutive', models.CharField(max_length=50)),
                ('estatus', models.CharField(max_length=25)),
                ('used', models.CharField(max_length=25)),
                ('onCustody', models.CharField(choices=[('S', 'S'), ('N', 'N')], default='N', max_length=1)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tapes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='sendHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formato', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sendhistory', to=settings.AUTH_USER_MODEL)),
                ('tape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sendhistory', to='api.tape')),
            ],
        ),
        migrations.CreateModel(
            name='recoverHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formato', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recoverhistory', to=settings.AUTH_USER_MODEL)),
                ('tape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recoverhistory', to='api.tape')),
            ],
        ),
        migrations.CreateModel(
            name='CustodyTape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custodyTape', to=settings.AUTH_USER_MODEL)),
                ('tape', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custodyTape', to='api.tape')),
            ],
        ),
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutive', models.CharField(max_length=50)),
                ('tool', models.CharField(max_length=50)),
                ('security', models.CharField(max_length=50)),
                ('copyType', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('storage_size', models.FloatField()),
                ('storaget_at', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to=settings.AUTH_USER_MODEL)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='api.element')),
                ('frecuency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='api.frecuency')),
                ('tape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='api.tape')),
            ],
        ),
        migrations.CreateModel(
            name='TapeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tapeTypeCode', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=25)),
                ('size', models.FloatField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TapeTypes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tape',
            name='tapeType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tapes', to='api.tapetype'),
        ),
    ]