# Generated by Django 5.0.7 on 2025-01-15 22:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '000X_add_user_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='used_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='recoverhistory',
            name='used_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='sendhistory',
            name='used_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='tape',
            name='used_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='backup',
            name='consecutive',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='backup',
            name='tool',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='copiedinformation',
            name='copiedInf',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='element',
            name='elementCode',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='elementType',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='frecuency',
            name='valueCode',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='recoverhistory',
            name='formato',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.RemoveField(
            model_name='recoverhistory',
            name='tape',
        ),
        migrations.AlterField(
            model_name='sendhistory',
            name='formato',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.RemoveField(
            model_name='sendhistory',
            name='tape',
        ),
        migrations.AlterField(
            model_name='supportedserviced',
            name='serviceType',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='tape',
            name='consecutive',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tapetype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tapetype',
            name='tapeTypeCode',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Cloud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clouds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CloudBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutive', models.CharField(max_length=50, unique=True)),
                ('tool', models.CharField(max_length=150)),
                ('copyType', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('storage_size', models.FloatField()),
                ('storaget_at', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloudBackups', to=settings.AUTH_USER_MODEL)),
                ('cloud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloudBackups', to='api.cloud')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloudBackups', to='api.element')),
                ('frecuency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloudBackups', to='api.frecuency')),
            ],
        ),
        migrations.AddField(
            model_name='recoverhistory',
            name='tape',
            field=models.ManyToManyField(related_name='recoverhistory', to='api.tape'),
        ),
        migrations.AddField(
            model_name='sendhistory',
            name='tape',
            field=models.ManyToManyField(related_name='sendhistory', to='api.tape'),
        ),
    ]
